[package]
name = "inso-code"
version = "0.1.0"
description = "Inso Code Desktop App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "inso_code_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-opener = "2"
tauri-plugin-shell = "2"
tauri-plugin-fs = "2"
window-vibrancy = "0.6.0"
objc = "0.2"
rfd = "0.14"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
aes-gcm = "0.10.3"
rand = "0.8.5"
base64 = "0.22.1"
tokio = { version = "1.37", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite"] }
xcap = "0.0.12"
lsp-types = "0.94"
headless_chrome = "1.0.12"
anyhow = "1.0"
lopdf = "0.32.0"
rusty-tesseract = "1.1.10"
azure_identity = "0.21"
azure_core = "0.21"
url = "2.5"
secrecy = "0.8"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
azure_storage_blobs = "0.21"
azure_security_keyvault = "0.21"
tree-sitter = "0.22"
enigo = "0.2"
tiktoken-rs = "0.5"
tantivy = "0.22"


