import React, { useState, useEffect, useRef } from 'react';
import { invoke } from '@tauri-apps/api/core';
import Editor, { DiffEditor, useMonaco } from '@monaco-editor/react';
import { Canvas, useFrame } from '@react-three/fiber';
import { OrbitControls, Instances, Instance } from '@react-three/drei';
import * as THREE from 'three';
import './App.css';

// ==============================================================================
// 1. HOLOGRAM UI (THREE.JS)
// ==============================================================================
function HolographicSwarm({ activeNodes }: { activeNodes: number }) {
  const ref = useRef<any>();
  useFrame((state) => {
    if (ref.current) ref.current.rotation.y = state.clock.elapsedTime * 0.2;
  });

  return (
    <Canvas camera={{ position: [0, 2, 5], fov: 45 }} gl={{ alpha: true }}>
      <ambientLight intensity={0.5} />
      <pointLight position={[10, 10, 10]} color="#00FF9D" intensity={2} />
      <group ref={ref}>
        <Instances limit={100} range={activeNodes}>
          <boxGeometry args={[0.1, 0.1, 0.1]} />
          <meshBasicMaterial color="#00FF9D" wireframe />
          {Array.from({ length: 100 }).map((_, i) => (
            <Instance 
              key={i} 
              position={[
                (Math.random() - 0.5) * 3, 
                (Math.random() - 0.5) * 3, 
                (Math.random() - 0.5) * 3
              ]} 
            />
          ))}
        </Instances>
      </group>
      <OrbitControls enableZoom={false} autoRotate autoRotateSpeed={2.0} />
    </Canvas>
  );
}

// ==============================================================================
// 2. MAIN APPLICATION (React)
// ==============================================================================
export default function App() {
  // Global State
  const [activeTab, setActiveTab] = useState<'chat' | 'work' | 'code'>('code');
  const [telemetry, setTelemetry] = useState<any>(null);

  // Shared Chat State
  const [prompt, setPrompt] = useState('');
  const [messages, setMessages] = useState<{role: string, content: string}[]>([]);
  const [isStreaming, setIsStreaming] = useState(false);
  const endOfMessagesRef = useRef<HTMLDivElement>(null);

  // Code Tab State
  const monaco = useMonaco();
  const [code, setCode] = useState('// Sovereign Azure Enclave\n\nfunction initialize() {\n  return "Secured.";\n}');
  const [composerCode, setComposerCode] = useState('');
  const [viewMode, setViewMode] = useState<'editor' | 'diff'>('editor');
  const [activeNodes, setActiveNodes] = useState(3);

  // Work Tab State
  const [professionContext, setProfessionContext] = useState('Financial Analyst');

  useEffect(() => {
    endOfMessagesRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  useEffect(() => {
    invoke('initialize_sovereign_azure_openai').catch(console.error);
    const interval = setInterval(() => {
      invoke('get_swarm_telemetry').then((res) => setTelemetry(res)).catch(console.error);
    }, 1000);
    return () => clearInterval(interval);
  }, []);

  const handleSubmit = async (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' && prompt.trim() && !isStreaming) {
      const userMessage = prompt;
      setPrompt('');
      setIsStreaming(true);
      setMessages(prev => [...prev, { role: 'user', content: userMessage }]);
      setMessages(prev => [...prev, { role: 'assistant', content: 'Processing securely...' }]);

      try {
        if (activeTab === 'code') {
          setActiveNodes(prev => Math.min(prev + 5, 50));
          const payload = `[COMPOSER] ${userMessage}`;
          await invoke('execute_agent_mission', { missionId: Date.now().toString(), command: payload });
          
          setViewMode('diff');
          setComposerCode(`// Auto-generated by Azure Copilot Composer\n\n${userMessage}\n\nfunction optimized() {\n  return true;\n}`);
          
          setMessages(prev => {
            const newMsg = [...prev];
            newMsg[newMsg.length - 1].content = "Code diff generated. Please review.";
            return newMsg;
          });
        } 
        else if (activeTab === 'work') {
          // Send to White-Collar Engine
          setMessages(prev => {
            const newMsg = [...prev];
            newMsg[newMsg.length - 1].content = `[${professionContext} Agent] Analyzing data and generating Excel structure... Done.`;
            return newMsg;
          });
        }
        else {
          // Standard Chat
          setMessages(prev => {
            const newMsg = [...prev];
            newMsg[newMsg.length - 1].content = "This is a conversational response from the Sovereign Azure Enclave.";
            return newMsg;
          });
        }
      } catch (err) {
        setMessages(prev => {
          const newMsg = [...prev];
          newMsg[newMsg.length - 1].content = `System Halt: ${err}`;
          return newMsg;
        });
      } finally {
        setIsStreaming(false);
        setActiveNodes(3);
      }
    }
  };

  return (
    <div className="layout" style={{ height: '100vh', display: 'flex', flexDirection: 'column', background: '#0a0a0a', color: '#fff' }}>
      
      {/* Titlebar */}
      <div data-tauri-drag-region style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 20px', background: '#111', borderBottom: '1px solid #333' }}>
        <div style={{ fontWeight: 'bold', letterSpacing: '2px', color: '#00FF9D' }}>ALTI.CODE.STUDIO</div>
        
        {/* The 3 Core Routing Tabs */}
        <div style={{ display: 'flex', gap: '20px' }}>
          <button onClick={() => setActiveTab('chat')} style={{ background: activeTab === 'chat' ? '#00FF9D20' : 'transparent', color: activeTab === 'chat' ? '#00FF9D' : '#888', border: '1px solid', borderColor: activeTab === 'chat' ? '#00FF9D' : 'transparent', padding: '5px 15px', borderRadius: '4px', cursor: 'pointer' }}>CHAT</button>
          <button onClick={() => setActiveTab('work')} style={{ background: activeTab === 'work' ? '#00FF9D20' : 'transparent', color: activeTab === 'work' ? '#00FF9D' : '#888', border: '1px solid', borderColor: activeTab === 'work' ? '#00FF9D' : 'transparent', padding: '5px 15px', borderRadius: '4px', cursor: 'pointer' }}>WORK</button>
          <button onClick={() => setActiveTab('code')} style={{ background: activeTab === 'code' ? '#00FF9D20' : 'transparent', color: activeTab === 'code' ? '#00FF9D' : '#888', border: '1px solid', borderColor: activeTab === 'code' ? '#00FF9D' : 'transparent', padding: '5px 15px', borderRadius: '4px', cursor: 'pointer' }}>CODE</button>
        </div>

        <div style={{ fontSize: '12px', color: '#888' }}>
          <span style={{ color: '#00FF9D', marginRight: '8px' }}>●</span> AZURE VNET NATIVE
        </div>
      </div>

      <div style={{ display: 'flex', flex: 1, overflow: 'hidden' }}>
        
        {/* ========================================================= */}
        {/* TAB 1: CHAT (Standard Conversational)                       */}
        {/* ========================================================= */}
        {activeTab === 'chat' && (
          <div style={{ flex: 1, display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
             <div style={{ width: '800px', height: '100%', display: 'flex', flexDirection: 'column' }}>
                <div style={{ padding: '40px', textAlign: 'center', opacity: 0.5 }}>
                   <h2>Sovereign Chat Engine</h2>
                   <p>Strictly conversational inference with memory persistence.</p>
                </div>
                {/* Messages mapped globally below */}
             </div>
          </div>
        )}

        {/* ========================================================= */}
        {/* TAB 2: WORK (White Collar - Excel/PDF/PPTX)                 */}
        {/* ========================================================= */}
        {activeTab === 'work' && (
          <div style={{ flex: 1, display: 'flex', padding: '20px', gap: '20px' }}>
            <div style={{ flex: 1, border: '1px dashed #444', borderRadius: '8px', padding: '20px', display: 'flex', flexDirection: 'column' }}>
              <h3 style={{ color: '#00FF9D', marginBottom: '10px' }}>Domain Persona Configuration</h3>
              <select 
                value={professionContext} 
                onChange={e => setProfessionContext(e.target.value)}
                style={{ background: '#222', color: '#fff', padding: '10px', border: '1px solid #444', borderRadius: '4px', marginBottom: '20px' }}>
                <option>Financial Analyst</option>
                <option>Corporate Lawyer</option>
                <option>Marketing Executive</option>
                <option>Supply Chain Manager</option>
                <option>HR Director</option>
              </select>

              <h3 style={{ color: '#00FF9D', marginBottom: '10px' }}>Sovereign Document Drop</h3>
              <div style={{ flex: 1, background: '#1a1a1a', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#666' }}>
                Drag & Drop PDFs, .docx, or .xlsx here for local VNet ingestion
              </div>
            </div>
            <div style={{ flex: 1, border: '1px solid #333', borderRadius: '8px', padding: '20px', background: '#111' }}>
              <h3 style={{ color: '#00FF9D', marginBottom: '10px' }}>Output Canvas</h3>
              <p style={{ color: '#888', fontSize: '13px' }}>Spreadsheets and Pitch Decks generated by the {professionContext} agent will preview here.</p>
            </div>
          </div>
        )}

        {/* ========================================================= */}
        {/* TAB 3: CODE (Software Engineering Copilot)                  */}
        {/* ========================================================= */}
        {activeTab === 'code' && (
          <div style={{ flex: 1, display: 'flex', flexDirection: 'column', borderRight: '1px solid #333' }}>
            <div style={{ display: 'flex', background: '#151515', padding: '10px 15px', gap: '10px' }}>
                <button 
                  onClick={() => setViewMode('editor')}
                  style={{ background: viewMode === 'editor' ? '#222' : 'transparent', color: viewMode === 'editor' ? '#fff' : '#888', border: 'none', padding: '5px 10px', borderRadius: '4px' }}>
                  main.ts
                </button>
                <button 
                  onClick={() => setViewMode('diff')}
                  style={{ background: viewMode === 'diff' ? '#222' : 'transparent', color: viewMode === 'diff' ? '#00FF9D' : '#888', border: 'none', padding: '5px 10px', borderRadius: '4px' }}>
                  Composer Diff
                </button>
            </div>
            
            {viewMode === 'editor' ? (
              <Editor height="100%" theme="vs-dark" language="typescript" value={code} onChange={(val) => setCode(val || '')} />
            ) : (
              <DiffEditor height="100%" theme="vs-dark" language="typescript" original={code} modified={composerCode} />
            )}
          </div>
        )}

        {/* ========================================================= */}
        {/* UNIVERSAL RIGHT SIDEBAR (Agent Command & Telemetry)       */}
        {/* ========================================================= */}
        <div style={{ width: '400px', display: 'flex', flexDirection: 'column', background: '#111', borderLeft: '1px solid #333' }}>
          
          <div style={{ height: '150px', borderBottom: '1px solid #333' }}>
            <HolographicSwarm activeNodes={activeNodes} />
          </div>

          <div style={{ flex: 1, overflowY: 'auto', padding: '20px' }}>
            {messages.map((msg, i) => (
              <div key={i} style={{ marginBottom: '15px', background: msg.role === 'user' ? '#222' : '#00FF9D10', padding: '12px', borderRadius: '6px', border: msg.role === 'assistant' ? '1px solid #00FF9D40' : 'none', color: '#ddd', fontSize: '14px' }}>
                {msg.content}
              </div>
            ))}
            <div ref={endOfMessagesRef} />
          </div>

          <div style={{ padding: '20px', borderTop: '1px solid #333' }}>
            <input 
              type="text" 
              placeholder={`Instruct the ${activeTab.toUpperCase()} Agent...`}
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              onKeyDown={handleSubmit}
              style={{ width: '100%', padding: '12px', background: '#222', border: '1px solid #444', borderRadius: '6px', color: '#fff', outline: 'none' }}
            />
          </div>

        </div>
      </div>
    </div>
  );
}
